### 1. user로 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

> {%
  client.test("Validate", function () {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
    client.assert(response.body.token.trim().length > 0);
  });

  client.log(response.body.token);
  client.global.set("token", "Bearer " + response.body.token)
%}

### 1. admin으로 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
  client.test("Validate", function () {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
    client.assert(response.body.token.trim().length > 0);
  });

  client.log(response.body.token);
  client.global.set("token", "Bearer " + response.body.token)
%}