### 1. home with token
GET http://localhost:8080/
Authorization: {{ token }}

### 2. user with token
GET http://localhost:8080/user
Authorization: {{ token }}

### 2-1. user
GET http://localhost:8080/user

### 3. admin with token
GET http://localhost:8080/admin
Authorization: {{ token }}

### 3. admin
GET http://localhost:8080/admin