server:
  port: 8081
spring:
  config:
    import: classpath:privacy.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            scope:
              - email
              - profile